#!/usr/bin/env ruby
# encoding: utf-8

$:.unshift File.dirname(__FILE__) + '/../library'
require 'mumble'

@client = Mumble::Client.new
@client.servers << Mumble::Server.new('uplink.io', 64738, username: 'meta')
@client.connect

# vim: syntax=ruby
